services:
  olipm:
    image: postgres:latest
    environment:
      POSTGRES_USER: superadmin
      POSTGRES_PASSWORD: superadmin
      POSTGRES_DB: olimp
    ports:
      - "5440:5432"
    volumes:
      - olimp_bd_data:/var/lib/postgresql/data
      - ./olimp/:/docker-entrypoint-initdb.d/
    networks:
      - less_5_network
volumes:
  olimp_bd_data:
networks:
  less_5_network:
      driver: bridge